name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  welcome:
    name: Welcome
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Welcome
    - run: echo "Welcome"
      uses: actions/setup-dotnet@v2
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
